# Generated by Django 4.1.3 on 2022-11-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0006_alter_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
