# Generated by Django 4.1.3 on 2022-11-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0008_product_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
